# Generated by Django 5.0 on 2023-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=152)),
                ('username', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
